Vagrant.configure("2") do |config|
  config.vm.box = "{{ cookiecutter.os }}"
  config.vm.hostname = "{{ cookiecutter.project_slug }}"
  config.vm.network "forwarded_port", id: 'ssh', guest: 22, host: 2222, host_ip: "127.0.0.1", auto_correct: false

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.name = "{{ cookiecutter.project_slug }}"
    virtualbox.memory = 8192
    virtualbox.cpus = 4
  end
end
